name: face
channels:
  - conda-forge
  - defaults
dependencies:
  - altgraph=0.17.5=pyhd8ed1ab_0
  - annotated-doc=0.0.4=pyhcf101f3_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.12.1=pyhcf101f3_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - dnspython=2.8.0=pyhcf101f3_0
  - email-validator=2.3.0=pyhd8ed1ab_0
  - email_validator=2.3.0=hd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - expat=2.7.3=h50f4ffc_4
  - fastapi=0.128.0=h0ea4129_1
  - fastapi-cli=0.0.20=pyhcf101f3_0
  - fastapi-core=0.128.0=pyhcf101f3_1
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httptools=0.7.1=py311haa24f5a_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h38cb7af_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.6=pyhcf101f3_1
  - libcxx=21.1.8=hb4ce287_0
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libsqlite=3.51.2=h1ae2325_0
  - libuv=1.51.0=h6caf38d_1
  - libzlib=1.3.1=h5f15de7_0
  - macholib=1.16.4=pyhd8ed1ab_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=pyh7db6752_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - ncurses=6.5=hee39554_0
  - openssl=3.6.1=hd24854e_1
  - packaging=25.0=py311hca03da5_1
  - pip=25.3=pyhc872135_0
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-core=2.41.5=py311h931abed_1
  - pydantic-extra-types=2.11.0=pyhd8ed1ab_0
  - pydantic-settings=2.12.0=pyh3cfb1c2_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyinstaller=6.18.0=py311hf78181e_0
  - pyinstaller-hooks-contrib=2026.0=pyhd8ed1ab_0
  - python=3.11.11=h89a136b_0_cpython
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-multipart=0.0.22=pyhcf101f3_0
  - python_abi=3.11=8_cp311
  - pyyaml=6.0.3=pyh7db6752_0
  - readline=8.3=h0b18652_0
  - rich=14.3.1=pyhcf101f3_0
  - rich-toolkit=0.17.1=pyhcf101f3_0
  - setuptools=80.10.1=py311hca03da5_0
  - shellingham=1.5.4=pyhd8ed1ab_2
  - sniffio=1.3.1=pyhd8ed1ab_2
  - sqlite=3.51.1=hab6afd1_0
  - starlette=0.50.0=pyhfdc7a7d_0
  - tk=8.6.15=hcd8a7d5_0
  - tomli=2.4.0=pyhcf101f3_0
  - typer=0.21.1=pyhf8876ea_0
  - typer-slim=0.21.1=pyhcf101f3_0
  - typer-slim-standard=0.21.1=h378290b_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=he532380_0
  - uvicorn=0.40.0=pyhc90fa1f_0
  - uvicorn-standard=0.40.0=h4cd5af1_0
  - uvloop=0.22.1=py311h8e34c70_1
  - watchfiles=1.1.1=py311h931abed_1
  - websockets=15.0.1=py311h80987f9_0
  - wheel=0.46.3=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h925e9cb_3
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - absl-py==2.4.0
      - astunparse==1.6.3
      - beautifulsoup4==4.14.3
      - blinker==1.9.0
      - charset-normalizer==3.4.4
      - deepface==0.0.98
      - filelock==3.20.3
      - fire==0.7.1
      - flask==3.1.2
      - flask-cors==6.0.2
      - flatbuffers==25.12.19
      - gast==0.7.0
      - gdown==5.2.1
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - gunicorn==24.1.1
      - h5py==3.15.1
      - itsdangerous==2.2.0
      - joblib==1.5.3
      - keras==3.13.1
      - libclang==18.1.1
      - lightdsa==0.0.3
      - lightecc==0.0.4
      - lightphe==0.0.20
      - lz4==4.4.5
      - markdown==3.10.1
      - ml-dtypes==0.5.4
      - mpmath==1.3.0
      - mtcnn==1.0.0
      - namex==0.1.0
      - numpy==2.4.1
      - opencv-python==4.13.0.90
      - opt-einsum==3.4.0
      - optree==0.18.0
      - pandas==3.0.0
      - pillow==12.1.0
      - protobuf==6.33.4
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - requests==2.32.5
      - retina-face==0.0.17
      - six==1.17.0
      - soupsieve==2.8.3
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.3.0
      - tf-keras==2.20.1
      - tqdm==4.67.1
      - urllib3==2.6.3
      - werkzeug==3.1.5
      - wrapt==2.0.1
prefix: /Users/ba.nguyen/anaconda3/envs/face
